### ISSUE TITLE
Error term of Fixed Factor in Random ANOVA don't match theory

### ISSUE THREAD

**Issue by agustavo87** [khliland/mixlm#1]
Hi, I was trying to run an analysis based on Maxwell & Delaney (2004, Table 10.5) and the output don't match textbooks results. Specifically the text says when we have a mixed factorial ANOVA (balanced) , the random factor (in this case `B` or `schools`) error term should be the `MS_within`. But in the results the interaction term is used, as it was a completly random model.
```R
# TABLE 10.5 ACT TRAINING EXAMPLE, Maxwell & Delaney, 2004, p. 482

library('tidyr')
library('mixlm')

Input =("
a1.b1	a1.b2 	a1.b3	a1.b4	a2.b1 	a2.b2 	a2.b3	a2.b4
28		26		24		20		30		34		31		33
26		26		24		20		28		31		29		30
26		25		19		20		28		29		25		28
23		21		14		18		25		27		21		26
17		17		14		12		19		24		19		23
")

schools <- read.table(textConnection(Input) , header = T)

schools.long = pivot_longer(
  schools,
  cols = a1.b1:a2.b4,
  names_sep = "\\.",
  names_to = c('treatment', 'school'),
  names_ptypes = factor(),
  values_to = "score"
)

mixlm <- lm(score ~ treatment * r(school),
            data = schools.long)
schools.anova =Anova(mixlm, type="III")
schools.anova

# F of B, according to textbook the Err.term is 4
F.B = schools.anova$anova$`Mean Sq`[2] / schools.anova$anova$`Mean Sq`[4]
F.B # 1.845

# p-value .159
pf(q=F.B,
   df1=schools.anova$anova$Df[2],
   df2=schools.anova$anova$Df[4],
   lower.tail=F) 
```
![image](https://user-images.githubusercontent.com/1779451/177005774-1f02820b-988f-45e1-a701-98a62502ff41.png)

I'm not sure if I'm using it wrong or may be this could be improved.

*Maxwell & Delaney (2004) Designing Experiments and Analyzing Data: A Model Comparison Perspective.*

**Comment by khliland** [comment]
Thank you for your detailed report, agustavo87!

This used to work correctly, but now denominator degrees of freedom act as if the model was only containing random terms. My implementation is based on DC Montgommery, but should be more or less universal. I will look into this and look for the bug!

Regards,
Kristian

**Comment by khliland** [comment]
Sorry, my bad!

It seems the book you are referring to uses the restricted model, while the default is the unrestricted model. The main difference between these two models is in the denominator degrees of freedom and SS for the random main effects. If you add the argument `, unrestricted=FALSE` to your `lm` call, you will get the behaviour you expected from your book.

Best regards,
Kristian

**Comment by agustavo87** [comment]
Oh, I see, I kind of suspected it, thanks!
